[i3.files]
"i3/config" = "~/.config/i3/config"
"i3/i3blocks/config" = "~/.config/i3blocks/config"

[fish.files]
"fish/config.fish" = "~/.config/fish/config.fish"

[picom.files]
"picom/config" = "~/.config/picom.comf"

[alacritty.files]
"alacritty/alacritty.yml" = "~/.alacritty.yml"