[i3.files]
"i3/config" = "~/.config/i3/config"
"i3/i3blocks/config" = "~/.config/i3blocks/config"

[i3-scrot.files]
"i3-scrot/config"="~/.config/i3-scrot.conf"

[fish.files]
"fish/config.fish" = "~/.config/fish/config.fish"

[picom.files]
"picom/config" = "~/.config/picom.conf"

[alacritty.files]
"alacritty/alacritty.yml" = "~/.alacritty.yml"

[libinput-gestures.files]
"libinput-gestures/config" = "~/.config/libinput-gestures.conf"