#!/bin/bash

getCurrentBattery() {
	acpi -b |  grep -o '[0-9]\+%' | tr -d '%' | sed -n 1p
}

getCurrentState() {
	acpi -b | grep -wo "Full\|Charging\|Discharging"
}

currentBattery=`getCurrentBattery`
state=`getCurrentState`

full=""
short=""

color=""
status=0
icon=""

if [[ $currentBattery -lt 15 ]]; then		# de 0% à 15%
	color="#ff0000"
	icon=""
	if [[ $state == "Discharging" ]] ; then
		notify-send "Battery low" "Battery level is $currentBattery%" 
	fi
elif [[ $currentBattery -lt 25 ]]; then	# de 15 à 25%
	color="#ff6100"
	icon=""
elif [[ $currentBattery -lt 50 ]]; then	# de 25 à 50%
	color="ffd000"
	icon=""
elif [[ $currentBattery -lt 75 ]]; then	# de 50 à 75%
	color="#bbff00"
	icon=""
else							# de 75 à 100%
	color="#00a500"
	icon=""
fi
if [[ $state == "Charging" ]] || [[ $state == "Full" ]] ; then
	icon=""
	color="#00a500"
fi
if [[ $state == "Full" ]] ; then
	notify-send "Battery full" "$currentBattery%"
fi


bold=$(tput bold)
normal=$(tput sgr0)

full="$currentBattery% $icon"
short="$cur"

echo $full
echo $short
echo $color
exit $status
