#!/bin/bash


newsig="pkill -RTMIN+14 i3blocks"

getCurrentHomeUsage() {
	df -h | grep /dev/sda4 | awk '{print $4}' | cut -dG -f1
}
getCurrentArchUsage() {
	df -h | grep /dev/sda6 | awk '{print $4}' | cut -dG -f1
}

curHome=`getCurrentHomeUsage`
curArch=`getCurrentArchUsage`

full=""
short=""
color=""
status=0
icon=""

if [[ $curHome -lt 5 ]] || [[ $curArch -lt 5 ]]; then		# de 0 à 5 Go disponibles
	color="#ff0000"
elif [[ $curHome -lt 15 ]] || [[ $curArch -lt 15 ]]; then	# de 5 à 15 Go disponibles
	color="#ff6100"
else
	color="#00a500"
fi

bold=$(tput bold)
normal=$(tput sgr0)

full="/home $curHome Go $icon $curArch Go /"
short="$cur"

echo $full
echo $short
echo $color
exit $status
